server:
  port: 8083

spring:
  application:
    name: notification-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/notificationdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        format_sql: true

minio:
  enabled: false

kafka:
  enabled: true

messaging:
  kafka:
    bootstrap-servers: ${KAFKA_BRK:localhost:9092}
    schema-registry-url: ${SCHEMA_REGISTRY_URL:http://localhost:8091/apis/ccompat/v7}
    group-id: notification-service-v4
    auto-offset-reset: earliest

notifications:
  templates:
    APL:
      title: "Vous êtes éligible à l'APL"
      message: "Vous pouvez bénéficier de l'Aide personnalisée au logement."

    CSS:
      title: "Vous êtes éligible à la Complémentaire Santé Solidaire"
      message: "Déposez votre demande dès maintenant."

    CHEQUE_ENERGIE:
      title: "Vous êtes éligible au Chèque Énergie"
      message: "Votre montant estimé est de {estimatedAmountLabel}."

    RSA:
      title: "Résultat de votre éligibilité au RSA"
      message: "{reason}"

logging:
  level:
    org.springframework.security: DEBUG # Logs globaux de Spring Security
    org.springframework.security.oauth2: DEBUG # Logs OAuth2 (JWT, Resource Server, etc.)
    org.springframework.security.web: DEBUG # Logs des requêtes HTTP et filtres
    org.springframework.boot.context.config: DEBUG # Logs de configuration (optionnel)
