sonar.projectKey=citizen-bff
sonar.projectName=citizen-bff

sonar.sources=src/main
sonar.tests=src/test

sonar.java.binaries=target/classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml