version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/frontend/portal-web"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/bff/citizens-bff"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/backend/core-services"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"