server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always

  tracing:
    sampling:
      probability: 1.0

  otlp:
    tracing:
      endpoint: http://jaeger:4317

spring:
  application:
    name: document-service

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/documentdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  flyway:
    enabled: false
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    secret: ${JWT_SECRET:my-super-secret-key-for-local-development-at-least-48-chars-long}

minio:
  enabled: true

kafka:
  enabled: true

storage:
  endpoint: ${STORAGE_ENDPOINT:http://localhost:9000}
  access-key: ${STORAGE_ACCESS_KEY:admin}
  secret-key: ${STORAGE_SECRET_KEY:admin123456}
  bucket: ${STORAGE_BUCKET:documents}

messaging:
  kafka:
    bootstrap-servers: ${KAFKA_BRK:localhost:9092}
    schema-registry-url: ${SCHEMA_REGISTRY_URL:http://localhost:8091/apis/ccompat/v7}
    group-id: document-service-v1
    auto-offset-reset: earliest

logging:
  level:
    org.springframework.security: DEBUG # Logs globaux de Spring Security
    org.springframework.security.oauth2: DEBUG # Logs OAuth2 (JWT, Resource Server, etc.)
    org.springframework.security.web: DEBUG # Logs des requêtes HTTP et filtres
    org.springframework.boot.context.config: DEBUG # Logs de configuration (optionnel)
    org.apache.kafka: DEBUG
    org.springframework.kafka: DEBUG
