server:
  port: 8084

spring:
  application:
    name: citizen-bff

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: citizen-bff
            client-secret: citizen-bff-secret
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI:http://localhost:9090/realms/govtech}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

services:
  profile:
    url: ${SERVICES_PROFILE_URL:http://localhost:8081}

  eligibility:
    url: ${SERVICES_ELIGIBILITY_URL:http://localhost:8082}

  notification:
    url: ${SERVICES_NOTIFICATION_URL:http://localhost:8083}

  document:
    url: ${SERVICES_DOCUMENT_URL:http://localhost:8085}

security:
  jwt:
    secret: ${JWT_SECRET:my-super-secret-key-for-local-development-at-least-32-chars}

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.boot.autoconfigure.security: DEBUG
