server:
  port: 8084

spring:
  application:
    name: citizen-bff
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET}
      client:
        registration:
          keycloak:
            client-id: citizen-bff
            client-secret: citizen-bff-secret
            scope:
              - openid
              - profile
              - email
            authorization-grant-type:
              authorization_code
            redirect-uri:
              "{baseUrl}/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri:
              http://localhost:9090/realms/govtech
        
       
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

services:
  identity:
    url: http://localhost:8086

  profile:
    url: http://localhost:8081

  eligibility:
    url: http://localhost:8082

  notification:
    url: http://localhost:8083

  document:
    url: http://localhost:8085

security:
  jwt:
    secret: ${JWT_SECRET}
    
