apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-floci
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: ai-public-benefits-platform
    app.kubernetes.io/component: infrastructure
spec:
  project: public-benefits

  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.20.2
    helm:
      releaseName: external-secrets
      values: |
        installCRDs: true

        serviceAccount:
          create: true
          name: external-secrets

        webhook:
          create: true

        certController:
          create: true

  destination:
    name: floci-gke-dev
    namespace: external-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

  revisionHistoryLimit: 5
