spring:
    kafka:
        bootstrap-servers: localhost:9092

        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: io.apicurio.registry.serde.avro.AvroKafkaSerializer

        properties:
            schema-registry-url: ${SCHEMA_REGISTRY_URL:http://localhost:8091/apis/ccompat/v7}

kafka:
    enabled: true

messaging:
    kafka:
        bootstrap-servers: ${KAFKA_BRK:localhost:9092}
        schema-registry-url: ${SCHEMA_REGISTRY_URL:http://localhost:8091/apis/ccompat/v7}

logging:
    level:
        org.springframework.kafka: DEBUG
        org.apache.kafka.clients.consumer: DEBUG
