services:   
  eligibility-service:
    build:
      context: ../../backend/core-services
      dockerfile: eligibility-service/Dockerfile
    container_name: eligibility-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/eligibilitydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres

  notification-service:
    build:
      context: ../../backend/core-services
      dockerfile: notification-service/Dockerfile
    container_name: notification-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/notificationdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres

  document-service:
    build:
      context: ../../backend/core-services
      dockerfile: document-service/Dockerfile
    container_name: document-service
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/documentdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      STORAGE_ENDPOINT: http://minio:9000
      STORAGE_ACCESS_KEY: admin
      STORAGE_SECRET_KEY: admin123456
      STORAGE_BUCKET: documents

      KAFKA_BRK: kafka:29092
      SCHEMA_REGISTRY_URL: http://apicurio-registry:8080/apis/ccompat/v7

    depends_on:
      - postgres
      - minio
  profile-service:
      build:
        context: ../../backend/core-services
        dockerfile: profile-service/Dockerfile
      container_name: profile-service

      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/profiledb
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres

      ports:
        - "8081:8081"
      depends_on:
        - postgres 



