global:
  scrape_interval: 15s

scrape_configs:

  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: citizen-bff
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - citizen-bff:8084

  - job_name: document-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - document-service:8085

  - job_name: kafka-exporter
    metrics_path: /metrics
    static_configs:
      - targets:
          - kafka-exporter:9308