server:
  port: 8081

spring:
  application:
    name: profile-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/profiledb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

#security:
#jwt:
#secret: ${JWT_SECRET:my-super-secret-key-for-local-development-at-least-48-chars-long}

minio:
  enabled: false

kafka:
  enabled: false

logging:
  level:
    org.springframework.security: DEBUG # Logs globaux de Spring Security
    org.springframework.security.oauth2: DEBUG # Logs OAuth2 (JWT, Resource Server, etc.)
    org.springframework.security.web: DEBUG # Logs des requêtes HTTP et filtres
    org.springframework.boot.context.config: DEBUG # Logs de configuration (optionnel)
    org.springframework.security.oauth2.server.resource: DEBUG
