server:
  port: 8061

spring:
  application:
    name: profile-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/profiledb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  flyway:
    enabled: false
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  jackson:
    deserialization:
      fail-on-unknown-properties: false

security:
  jwt:
    secret: ${JWT_SECRET:my-super-secret-key-for-local-development-at-least-48-chars-long}

minio:
  enabled: false

kafka:
  enabled: true

messaging:
  kafka:
    bootstrap-servers: ${KAFKA_BRK:localhost:9092}
    schema-registry-url: ${SCHEMA_REGISTRY_URL:http://localhost:8091/apis/ccompat/v7}
    group-id: profile-service-v13
    auto-offset-reset: earliest

  outbox:
    enabled: true
    fixed-delay: 5s
    batch-size: 100
    publishing-timeout: 30s
    stale-after: 5m

logging:
  level:
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.security.oauth2.server.resource: INFO
    org.springframework.security.web: INFO

    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: OFF

    org.springframework.kafka: DEBUG
    org.apache.kafka.clients.consumer: INFO
    org.springframework.kafka.listener: DEBUG
    org.springframework.kafka.listener.DefaultErrorHandler: DEBUG
    org.springframework.kafka.support: DEBUG

    org.springframework.boot.context.config: INFO
