server:
  port: 8096

spring:
  application:
    name: security-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/securitydb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        format_sql: true

minio:
  enabled: true

kafka:
  enabled: true

messaging:
  kafka:
    bootstrap-servers: ${KAFKA_BRK:localhost:9092}
    schema-registry-url: ${SCHEMA_REGISTRY_URL:http://localhost:8091/apis/ccompat/v7}
    group-id: security-service-v23
    auto-offset-reset: earliest

  outbox:
    enabled: true
    fixed-delay: 5s
    batch-size: 100
    publishing-timeout: 30s
    stale-after: 5m  

storage:
  endpoint: ${STORAGE_ENDPOINT:http://localhost:9000}
  access-key: ${STORAGE_ACCESS_KEY:admin}
  secret-key: ${STORAGE_SECRET_KEY:admin123456}

clamav:
  host: localhost
  port: 3310
  timeout: 5000

logging:
  level:
    org.springframework.kafka.listener.DefaultErrorHandler: DEBUG
    org.springframework.kafka.listener.KafkaMessageListenerContainer: DEBUG
