{
  "type": "record",
  "name": "DocumentBaseEvent",
  "namespace": "com.govtech.events.common",

  "fields": [
    {
      "name": "base",
      "type": "com.govtech.events.common.BaseEvent"
    },

    {
      "name": "documentId",
      "type": ["null", "long"],
      "default": null
    },

    {
      "name": "applicationId",
      "type": [
        "null",
        {
          "type": "string",
          "avro.java.string": "String"
        }
      ],
      "default": null
    },

    {
      "name": "bucket",
      "type": {
        "type": "string",
        "avro.java.string": "String"
      }
    },

    {
      "name": "objectKey",
      "type": {
        "type": "string",
        "avro.java.string": "String"
      }
    },

    {
      "name": "contentType",
      "type": {
        "type": "string",
        "avro.java.string": "String"
      }
    },

    {
      "name": "documentType",
      "type": "DocumentType"
    },

    {
      "name": "origin",
      "type": "com.govtech.events.common.DocumentOrigin"
    },

    {
      "name": "source",
      "type": [
        "null",
        {
          "type": "string",
          "avro.java.string": "String"
        }
      ],
      "default": null
    },

    {
      "name": "sha256",
      "type": [
        "null",
        {
          "type": "string",
          "avro.java.string": "String"
        }
      ],
      "default": null
    },

    {
      "name": "fileName",
      "type": [
        "null",
        {
          "type": "string",
          "avro.java.string": "String"
        }
      ],
      "default": null
    },

    {
      "name": "fileSize",
      "type": ["null", "long"],
      "default": null
    },

    {
      "name": "model",
      "type": [
        "null",
        {
          "type": "string",
          "avro.java.string": "String"
        }
      ],
      "default": null
    },

    {
      "name": "territoryCode",
      "type": [
        "null",
        {
          "type": "string",
          "avro.java.string": "String"
        }
      ],
      "default": null,
      "doc": "Territorial scope of the document."
    }
  ]
}
