{
  "type": "record",
  "name": "DocumentCreatedEvent",
  "namespace": "com.govtech.events.document",
  "doc": "Document successfully stored by document-service.",

  "fields": [

    {
      "name": "baseEvent",
      "type": "com.govtech.events.common.DocumentBaseEvent"
    },


    {
      "name": "storageProvider",
      "type": {
        "type": "string",
        "avro.java_string": "String"
      },
      "doc": "Storage provider used (MinIO, S3, GCS...)"
    },


    {
      "name": "version",
      "type": [
        "null",
        "int"
      ],
      "default": null
    }

  ]
}