spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BRK:kafka:29092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

    consumer:
      enable-auto-commit: false
      auto-offset-reset: latest

    listener:
      ack-mode: record

    properties:
      schema.registry.url: ${SCHEMA_REGISTRY_URL:http://schema-registry:8081}

messaging:
  kafka:
    dlt:
      replay:
        enabled: false

