sonar.projectKey=govtech-aides_core-services
sonar.projectName=govtech-aides-core-services

sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.tests=.

sonar.java.binaries=**/target/classes

sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml

sonar.exclusions=**/target/**,**/generated/**