server:
  port: 8082

spring:
  application:
    name: eligibility-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/eligibilitydb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  flyway:
    enabled: false
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    secret: ${JWT_SECRET:my-super-secret-key-for-local-development-at-least-48-chars-long}

minio:
  enabled: false

kafka:
  enabled: true

messaging:
  kafka:
    bootstrap-servers: ${KAFKA_BRK:localhost:9092}
    schema-registry-url: ${SCHEMA_REGISTRY_URL:http://localhost:8091/apis/ccompat/v7}
    group-id: eligibility-service-v17
    auto-offset-reset: earliest

eligibility:
  ars:
    income-ceiling: 30000
    estimated-amount: 423.48
    estimated-amount-label: "À partir de 423,48 € par enfant"
  css:
    income-ceiling: 12000
    estimated-amount: 30
    estimated-amount-label: "Prise en charge jusqu'à 100 % des dépenses de santé"
  rsa:
    max-income: 12000
    estimated-amount: 635.71
    estimated-amount-label: "635.71 €/mois"

  prime-activite:
    income-ceiling: 20000
    estimated-amount: 200
    estimated-amount-label: "À partir de 200 €/mois"
  apl:
    income-ceiling: 30000
    estimated-amount: 150
    estimated-amount-label: "Entre 150 € et 350 € / mois"

clients:
  profile:
    base-url: ${PROFILE_SERVICE:http://localhost:8081}

logging:
  level:
    org.springframework.security: DEBUG # Logs globaux de Spring Security
    org.springframework.security.oauth2: DEBUG # Logs OAuth2 (JWT, Resource Server, etc.)
    org.springframework.security.web: DEBUG # Logs des requêtes HTTP et filtres
    org.springframework.boot.context.config: DEBUG # Logs de configuration (optionnel)
