# .github/workflows/core-services.yml

name: Backend

on:
  pull_request:
    paths:
      - "backend/**"
  push:
    branches: [main]
    paths:
      - "backend/**"

jobs:
  core-services:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}

      - name: Build
        run: mvn clean verify -DskipITs=true

      - name: Upload Jacoco
        uses: actions/upload-artifact@v7
        with:
          name: jacoco
          path: target/site/jacoco
