name: Security



on:
  push:
    branches:
      - main
    paths:
      - 'backend/core-services/**'
      - 'bff/citizen-bff/**'
      - 'frontend/portal-web/**'

  pull_request:
    paths:
      - 'backend/core-services/**'
      - 'bff/citizen-bff/**'
      - 'frontend/portal-web/**'

jobs:

  security:

    runs-on: ubuntu-latest   

    steps:

      - uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          severity: HIGH,CRITICAL
          exit-code: "0"

      #- name: OWASP Dependency Check
        #working-directory: backend/core-services
        #run: mvn dependency-check:check